# Generated by Django 4.2.10 on 2024-02-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_instagram_url_artist_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='profile_image',
        ),
    ]
